name: amap_location_fluttify
description: An `Amap` Location Component, Powered By `Fluttify`, A Compiler Generating Dart Bindings For Native SDK.
version: 0.20.0-dev.1
author: yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project/amap_location_fluttify

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  amap_core_fluttify:
    git:
      url: https://github.com/boomcx/amap_map_fluttify.git
      path: dependencies/amap_core_fluttify
  
  foundation_fluttify:
    git:
      url: https://github.com/boomcx/amap_map_fluttify.git
      path: dependencies/foundation_fluttify
  core_location_fluttify:
    git:
      url: https://github.com/boomcx/amap_map_fluttify.git
      path: dependencies/core_location_fluttify

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_location_fluttify
        pluginClass: AmapLocationFluttifyPlugin
      ios:
        pluginClass: AmapLocationFluttifyPlugin