name: amap_search_fluttify
description: An `Amap Search` Map Component, Powered By `Fluttify`, A Compiler Generating Dart Bindings For Native SDK.
version: 0.18.0
homepage: https://github.com/fluttify-project

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  
  foundation_fluttify:
    git:
      url: https://github.com/boomcx/amap_map_fluttify.git
      path: dependencies/foundation_fluttify
  core_location_fluttify:
    git:
      url: https://github.com/boomcx/amap_map_fluttify.git
      path: dependencies/core_location_fluttify
  amap_core_fluttify:
    git:
      url: https://github.com/boomcx/amap_map_fluttify.git
      path: dependencies/amap_core_fluttify

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_search_fluttify
        pluginClass: AmapSearchFluttifyPlugin
      ios:
        pluginClass: AmapSearchFluttifyPlugin