name: uni_map_platform_interface
description: Uni Map Platform Interface.
version: 0.7.0-rc.0

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  foundation_fluttify:
    git:
      url: https://github.com/boomcx/amap_map_fluttify.git
      path: dependencies/foundation_fluttify
  core_location_fluttify:
    git:
      url: https://github.com/boomcx/amap_map_fluttify.git
      path: dependencies/core_location_fluttify

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4