name: amap_core_fluttify
description: An `Amap Core` Map Component, Powered By `Fluttify`, A Compiler Generating Dart Bindings For Native SDK.
version: 0.17.0
homepage: https://github.com/fluttify-project

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  
  foundation_fluttify:
    path: ../foundation_fluttify
  core_location_fluttify:
    path: ../core_location_fluttify

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_core_fluttify
        pluginClass: AmapCoreFluttifyPlugin
      ios:
        pluginClass: AmapCoreFluttifyPlugin