name: core_location_fluttify
description: A new Flutter project.
version: 0.7.1
author: yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project/core_location_fluttify

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  foundation_fluttify:
    git:
      url: https://github.com/boomcx/amap_map_fluttify.git
      path: dependencies/foundation_fluttify

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.core_location_fluttify
        pluginClass: CoreLocationFluttifyPlugin
      ios:
        pluginClass: CoreLocationFluttifyPlugin